title: Funnel Charts for PowerBI
description: A PowerBI Custom Visual for Funnel Charts
theme: just-the-docs

url: https://aus-doh-safety-and-quality.github.io/PowerBI-Funnels/

aux_links:
  GitHub Repository: https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-Funnels

math: mathjax
