---
name: "Build release"

on:
  workflow_dispatch:

jobs:
  build-pbiviz-packages:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js 10.x
      uses: actions/setup-node@v6
      with:
        node-version: 20.x

    - name: Label visuals as 'Development'
      run: |
        sed -i 's/"name":"PBIFunnels"/"name":"PBIFunnels_DEV"/g' pbiviz.json
        sed -i 's/"displayName":"Funnel Plots"/"displayName":"Funnel Plots (Dev)"/g' pbiviz.json
        sed -i 's/"guid":"PBIFUN"/"guid":"PBIFUN_DEV"/g' pbiviz.json
      shell: bash

    - name: Build
      run: |
        npm install
        npm install -g powerbi-visuals-tools
        pbiviz package

    - name : "Create Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: dist/*.pbiviz
