name: Push to Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm install -g powerbi-visuals-tools@3.1.15
        pbiviz package
        
    - name: Update release
      uses: johnwbyrd/update-release@v1.0.0
      with:
        release: "Continuous Building"
        body: "This release contains the latest build of the visual"
        message: "This release contains the latest build of the visual"
        token: ${{ secrets.GITHUB_TOKEN }}
        files: dist/PBIFUN.1.0.0.pbiviz
